services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=hurryupbaby
      - POSTGRES_DB=hurryup
    volumes:
      - register_pg_data:/bitnami/postgresql

volumes:
  register_pg_data: